/**
 * ============================================================
 * AESTHETICS THERAPY — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on June 16, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Aesthetics Therapy",
  "tagline": "Reconnect with your natural radiant glow.",
  "preloaderTagline": "Associates in Womens Health",
  "copyrightText": "",
  "logoPrimary": "logos/aesthetics therapy-wht.png",
  "logoAlternate": "logos/aesthetics-logo.png",
  "logoHeaderChoice": "primary",
  "logoHeaderHeight": 50,
  "logoSplashChoice": "alternate",
  "logoSplashHeight": 200,
  "logoSplashMode": "logo-tagline",
  "logoFooterChoice": "alternate",
  "logoFooterHeight": 100,
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "Our Team",
      "subtitle": ""
    },
    "contact": {
      "label": "Contact Us"
    }
  },
  "attorneyName": "Hanna White",
  "attorneyDegree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
  "attorneyCredentials": [
    "Sigma Theta Tau International Honor Society",
    "American Association of Nurse Practitioners",
    "Chattanooga Area Nurses in Advanced Practice"
  ],
  "aboutBio1": "",
  "aboutBio2": "",
  "attorneyPhoto": "us/white-01.png",
  "aboutNavLabel": "About Us",
  "attorneys": [
    {
      "name": "Hanna White",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "us/white-01.png",
      "credentials": [
        "Sigma Theta Tau International Honor Society",
        "American Association of Nurse Practitioners",
        "Chattanooga Area Nurses in Advanced Practice"
      ],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "(423) 910-0896",
  "phoneRaw": "14239100896",
  "fax": "",
  "email": "",
  "address": "6845 Mountain View Rd",
  "city": "Ooltewah",
  "state": "Tennessee",
  "stateAbbr": "TN",
  "zip": "37363",
  "locations": [
    {
      "name": "Associates in Women's Health Ooltewah",
      "phone": "(423) 910-0896",
      "phoneRaw": "14239100896",
      "fax": "",
      "email": "",
      "address": "6845 Mountain View Rd",
      "city": "Ooltewah",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37363",
      "hours": [
        {
          "days": "Mon - Thu",
          "hours": "9:00 - 4:00pm"
        }
      ]
    }
  ],
  "hours": [
    {
      "days": "Mon - Thu",
      "hours": "9:00 - 4:00pm"
    }
  ],
  "socialLinks": [
    {
      "platform": "facebook",
      "url": "https://www.facebook.com/share/14h3zg8s7kp/"
    }
  ],
  "stats": [],
  "colors": {
    "navy": "#392b5a",
    "navyLight": "#392b5a",
    "gold": "#bb6eff",
    "goldLight": "#ae52fe",
    "goldPale": "#faf6ec",
    "warmWhite": "#ebe5f1",
    "cream": "#e5ddee",
    "chrome": "#392b5a"
  },
  "fontColors": {
    "heading": "#392b5a",
    "body": "#2a1f41",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Lora",
  "fontBody": "Assistant",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#000000",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#000000",
    "overlayOpacity": 0.3,
    "videoClips": [
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 8
      },
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-02.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 4,
        "playDuration": 8
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Reconnect with your natural radiant glow.",
  "heroSubline": "At Aesthetic Therapy, we believe your true beauty isn’t something we create, but something we expertly reveal. Our specialized procedures are designed to highlight your unique features and restore the natural, youthful glow that has always been there. By blending clinical precision with an artistic eye, we help you achieve a refreshed look that feels both effortless and authentically you. Step into a more confident version of yourself and let your inner radiance take center stage.",
  "heroTrustBullets": [],
  "heroPrimaryLabel": "Our Treatments",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "our-treatments",
  "heroSecondaryLabel": "Contact Us",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "contact",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "Location & Phone Information",
  "contactSubline": "We are located in the Associates in Women's Health building on the left hand side.\n\nStop in to see us or send us a message and let us know what your interested in so that we can reach out to you to set up an appointment.",
  "contactFormHeading": "Send Us a Message",
  "contactFormIntro": "Interested in a treatment, would like to schedule a consultation, or would just like to let us know how we are doing? Use this form and reach out to us.",
  "contactPrivacyNote": "Privacy is a top concern. We do not use or sell your information to any other parties. ",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Contact Us",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "location",
      "navLabel": "Location",
      "emoji": "🏚️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "locations",
          "label": "Our Location",
          "background": "alt",
          "anchorId": "our-location",
          "displayMode": "cards",
          "layoutMode": "top",
          "featureSide": "left",
          "mapMode": "linkout",
          "maxCols": 2,
          "showHours": true,
          "items": [
            {
              "locationIndex": "0",
              "imagePath": "us/office-ooltewah-01.png"
            }
          ]
        }
      ]
    },
    {
      "slug": "our-treatments",
      "navLabel": "Our Treatments",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "pricing",
          "label": "Body Lab",
          "background": "light",
          "anchorId": "hormone-replacement-therapy",
          "heading": "Our Treatments",
          "subtitle": "",
          "maxCols": 2,
          "colFullWidth": true,
          "items": [
            {
              "name": "Hormone Replacement Therapy: For Women",
              "tagline": "We believe that every woman deserves to feel vibrant, balanced, and empowered in her own body. The journey of womanhood is marked by profound hormonal shifts, from the first menstrual cycle to perimenopause, menopause, and beyond. These changes can bring a host of disruptive symptoms, but you do not have to accept fatigue, mood swings, brain fog, or weight gain as an inevitable part of life.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/hrt/AdobeStock_617368354-scaled-1200x0-c-default.webp",
              "imageSize": "md",
              "ribbon": "",
              "note": "",
              "cardStyle": "alt",
              "featured": false,
              "cta_linkLabel": "Information: HRT for Women",
              "cta_linkType": "internal",
              "cta_linkUrl": "hormone-replacement",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Hormone Replacement Therapy: For Men",
              "tagline": "We believe that every man deserves to feel powerful, sharp, and fully in control of his health. The modern man faces unique challenges, from the natural hormonal decline of andropause to the relentless pressures of career and life, which can diminish energy, sap motivation, and impact performance. You do not have to accept fatigue, brain fog, low libido, or stubborn weight gain as your new normal.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/hrt/AdobeStock_1418257616-scaled-1200x0-c-default.webp",
              "imageSize": "md",
              "ribbon": "",
              "note": "",
              "cardStyle": "alt",
              "featured": false,
              "cta_linkLabel": "Information: HRT for Men",
              "cta_linkType": "internal",
              "cta_linkUrl": "hormone-replacement",
              "cta_anchorId": "hrt-men",
              "features": []
            },
            {
              "name": "Hair Removal",
              "tagline": "Intense Pulsed Light (IPL) and Fractional Laser treatments are distinct skin rejuvenation technologies. IPL uses broad-spectrum light to treat surface issues like sun spots, pigmentation, and redness. Fractional lasers create microscopic treatment zones to stimulate collagen, treating deeper, more severe wrinkles and scars.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/ipl/hair removal-01.jpeg",
              "imageSize": "md",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": false,
              "cta_linkLabel": "Information: Hair Removal",
              "cta_linkType": "internal",
              "cta_linkUrl": "hair-removal",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Skin Revitalization",
              "tagline": "Skin revitalization treatments are non-surgical procedures designed to improve skin quality, texture, and tone by stimulating the body's natural healing response.\nUnlike surgical facelifts, these treatments primarily target surface-level issues like fine lines, sun damage, acne scars, and uneven pigmentation.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/skincare/skin revitalization-01.jpg",
              "imageSize": "md",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": false,
              "cta_linkLabel": "Information: Skin Revitalization",
              "cta_linkType": "internal",
              "cta_linkUrl": "skin-revitalization",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Body Contouring & Sculpting",
              "tagline": "Even with diet and exercise, most people have stubborn pockets of fat that seem impossible to lose. Aesthetic Therapy is proud to offer truSculpt® iD, a revolutionary non-surgical, body-sculpting treatments that allows you to personalize your ideal body in as little as one 15-minute treatment.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/trusculpt/trusculpt-1024x768.webp",
              "imageSize": "md",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": false,
              "cta_linkLabel": "Information: Body Contouring & Sculpting",
              "cta_linkType": "internal",
              "cta_linkUrl": "body-contouring",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "services",
          "label": "Beauty Lab",
          "background": "light",
          "anchorId": "our-treatments",
          "heading": "Our Treatments",
          "subtitle": "We offer a variety of services...",
          "maxCols": 2,
          "colFullWidth": true,
          "items": [
            {
              "icon": "🏵️",
              "title": "Hormone Replacement",
              "desc": "",
              "detail": "Start feeling like you again.",
              "btnLabel": "Learn More About Hormone Replacement",
              "btnLinkType": "internal",
              "btnLinkUrl": "hormone-replacement",
              "btnAnchorId": "",
              "imagePath": "images/basic facial-01.webp",
              "imageSize": "full"
            },
            {
              "icon": "🏵️",
              "title": "Hair Removal",
              "desc": "Intense Pulsed Light (IPL) and Fractional Laser treatments are distinct skin rejuvenation technologies.",
              "detail": "IPL uses broad-spectrum light to treat surface issues like sun spots, pigmentation, and redness. Fractional lasers create microscopic treatment zones to stimulate collagen, treating deeper, more severe wrinkles and scars.",
              "btnLabel": "Hair Removal",
              "btnLinkType": "internal",
              "btnLinkUrl": "hair-removal",
              "btnAnchorId": "",
              "imagePath": "images/ipl/hair removal-01.jpeg",
              "imageSize": "full"
            },
            {
              "icon": "🏵️",
              "title": "Skin Revitalization",
              "desc": "Skin revitalization treatments are non-surgical procedures designed to improve skin quality, texture, and tone by stimulating the body's natural healing response.",
              "detail": "Unlike surgical facelifts, these treatments primarily target surface-level issues like fine lines, sun damage, acne scars, and uneven pigmentation.",
              "btnLabel": "Skin Revitalization Treatments",
              "btnLinkType": "internal",
              "btnLinkUrl": "skin-revitalization",
              "btnAnchorId": "",
              "imagePath": "images/skin revitalization-01.jpg",
              "imageSize": "full"
            },
            {
              "icon": "🏵️",
              "title": "Body Contouring & Sculpting",
              "desc": "Even with diet and exercise, most people have stubborn pockets of fat that seem impossible to lose.",
              "detail": "Aesthetic Therapy is proud to offer truSculpt® iD and SculpSure, revolutionary non-surgical, body-sculpting treatments that allows you to personalize your ideal body in as little as one 15-minute treatment.",
              "btnLabel": "",
              "btnLinkType": "internal",
              "btnLinkUrl": "body-contouring",
              "btnAnchorId": "",
              "imagePath": "images/skin revitalization-01.jpg",
              "imageSize": "full"
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "external",
          "secondary_linkLabel": "Test",
          "secondary_linkUrl": "https://auspider98.github.io/AWH/index.html",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "hormone-replacement",
      "navLabel": "Hormone Replacement",
      "emoji": "🧬",
      "enabled": true,
      "parent": "our-treatments",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Hormone Replacement Therapy",
          "background": "light",
          "anchorId": "hrt-women",
          "heading": "For Women: Understand Your Body, Reclaim Your Energy, and Thrive at Every Stage of Life.",
          "body": "We believe that every woman deserves to feel vibrant, balanced, and empowered in her own body. The journey of womanhood is marked by profound hormonal shifts, from the first menstrual cycle to perimenopause, menopause, and beyond. These changes can bring a host of disruptive symptoms, but you do not have to accept fatigue, mood swings, brain fog, or weight gain as an inevitable part of life.\nWe go beyond surface-level symptom management to address the root cause of hormonal imbalance, using a sophisticated, whole-body approach that combines advanced science with compassionate, individualized care.",
          "imagePath": "images/hrt/AdobeStock_617368354-scaled-1200x0-c-default.webp",
          "imagePosition": "left",
          "imageMaxWidth": "500",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext",
          "richContent": "<h2>Your Comprehensive Guide to Hormonal Wellness</h2><div><p>Navigating your health can feel overwhelming. This section is designed to be your trusted resource, providing clear, in-depth information on the key aspects of female hormonal health. Explore our core pages to understand your body better and discover the solutions that can help you feel like yourself again.</p></div>",
          "imagePath": "images/hrt/AdobeStock_1522975617-scaled-1200x0-c-default.webp",
          "imagePos": "right",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext-2",
          "richContent": "<h2 style=\"\">Understanding Hormonal Imbalance</h2><div><p>It all begins with understanding&nbsp;what&nbsp;is happening inside your body and&nbsp;why. Our foundational pages provide a complete overview of the intricate world of female hormones.</p><ul><li>Hormonal Imbalance Women: Get a comprehensive overview of what hormonal imbalance is, how it affects your well-being, and how the EvexiPEL Method provides a definitive path to restoring your body’s natural harmony</li><li>Symptoms of Hormonal Imbalance: Do you feel \"off\" but can't pinpoint the reason? This page details the most common physical, emotional, and cognitive signs of hormonal imbalance, helping you connect your symptoms to their underlying cause</li><li>Causes of Hormonal Imbalance: From the natural process of aging, perimenopause, and menopause to conditions like PCOS, thyroid dysfunction, and chronic stress, this section explores the primary drivers of hormonal disruption women</li></ul></div>",
          "imagePath": "",
          "imagePos": "none",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext-2",
          "richContent": "<h2>Our Solutions: A Personalized Approach to Healing</h2><p>At Aesthetics Therapy, we don't believe in one-size-fits-all solutions. Our therapies are tailored to your unique biology, using advanced diagnostics and cutting-edge treatments to achieve lasting results. Your journey begins with Hormone Imbalance Testing, which gives us the precise data needed to create your personalized roadmap to wellness.</p>",
          "imagePath": "images/hrt/AdobeStock_233485605-scaled-1200x0-c-default.webp",
          "imagePos": "right",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext-3",
          "richContent": "<h2>Hormone Optimization Therapy: Restoring Your Foundation</h2><p>This is the cornerstone of our approach. We use Bioidentical Hormone Replacement Therapy (BHRT), delivered via our proprietary EvexiPEL Method, to safely and effectively restore your body's natural hormonal balance. Using plant-based hormone pellets, we replenish hormones like estrogen, progesterone, and testosterone to their optimal levels. This provides consistent, steady relief from disruptive symptoms, helping you feel energized, clear-headed, and emotionally stable again.</p>",
          "imagePath": "images/hrt/AdobeStock_138553634-scaled-1200x0-c-default.webp",
          "imagePos": "left",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "two-col",
          "label": "Hormone Replacement Therapy",
          "background": "alt",
          "anchorId": "hrt-men",
          "heading": "For Men: Understand Your Body, Reclaim Your Energy, and Thrive at Every Stage of Life.",
          "body": "We believe that every man deserves to feel powerful, sharp, and fully in control of his health. The modern man faces unique challenges, from the natural hormonal decline of andropause to the relentless pressures of career and life, which can diminish energy, sap motivation, and impact performance. You do not have to accept fatigue, brain fog, low libido, or stubborn weight gain as your new normal.",
          "imagePath": "images/hrt/AdobeStock_1418257616-scaled-1200x0-c-default.webp",
          "imagePosition": "left",
          "imageMaxWidth": "500",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        }
      ]
    },
    {
      "slug": "hair-removal",
      "navLabel": "Hair Removal",
      "emoji": "💈",
      "enabled": true,
      "parent": "our-treatments",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "pricing",
          "label": "Treatments",
          "background": "alt",
          "anchorId": "laser-hair-removal",
          "heading": "Laser Hair Removal",
          "subtitle": "",
          "maxCols": 1,
          "colFullWidth": true,
          "items": [
            {
              "name": "IPL Fractional Laser",
              "tagline": "Intense Pulsed Light (IPL) and Fractional Laser treatments are distinct skin rejuvenation technologies. IPL uses broad-spectrum light to treat surface issues like sun spots, pigmentation, and redness. Fractional lasers create microscopic treatment zones to stimulate collagen, treating deeper, more severe wrinkles and scars.",
              "price": "$250-$475",
              "period": "/ Session",
              "icon": "",
              "imagePath": "images/ipl/hair removal-01.jpeg",
              "imageSize": "lg",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "IPL (Intense Pulsed Light)",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Best for reducing hyperpigmentation, age spots, and rosacea. It offers 1–3 days of downtime.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Fractional Laser",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Preferred for deeper resurfacing, improving skin texture, and severe acne scars. It requires more downtime (3–7 days) but produces more dramatic results.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Targeting",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "IPL covers a broad area evenly, whereas fractional lasers target only a fraction of the skin (microscopic columns), leaving surrounding tissue intact for faster healing.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Suitability",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "IPL is generally best for lighter skin tones, as it can burn olive or tanned skin.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Combination",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "We combine both, using IPL for surface color correction and fractional lasers for texture correction.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Maintenance",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "IPL requires 3–4 sessions 2–4 weeks apart, while fractional lasers may require fewer, more spaced-out sessions depending on the severity.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Both treatments require avoiding sun exposure and using sunscreen post-procedure to see the best results.",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "skin-revitalization",
      "navLabel": "Skin Revitalization",
      "emoji": "📄",
      "enabled": true,
      "parent": "our-treatments",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "pricing",
          "label": "Treatments",
          "background": "dark",
          "anchorId": "skin-revitalization",
          "heading": "Skin Revitalization",
          "subtitle": "Skin revitalization treatments are non-surgical procedures designed to improve skin quality, texture, and tone by stimulating the body's natural healing response. Unlike surgical facelifts, these treatments primarily target surface-level issues like fine lines, sun damage, acne scars, and uneven pigmentation.",
          "maxCols": 1,
          "colFullWidth": true,
          "items": [
            {
              "name": "Skin Revitalization",
              "tagline": "",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "images/skincare/skin revitalization-01.jpg",
              "imageSize": "lg",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "fees",
          "label": "Treatments",
          "background": "alt",
          "anchorId": "skin-revitalization-table",
          "heading": "Skin Revitalization",
          "subtitle": "Comparison of Common Procedures",
          "col1Label": "Targets Best",
          "col2Label": "Treatment",
          "col3Label": "Sessions (Recovery)",
          "disclaimer": "",
          "items": [
            {
              "service": "Deep wrinkles, scars, sun damage",
              "amount": "Laser",
              "detail": "1-3 Sessions (2-14 Days)",
              "note": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "service": "Texture, large pores, minor scars",
              "amount": "Microneedling",
              "detail": "3–6 sessions (1-3 Days)",
              "note": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "service": "Rosacea, redness, age spots",
              "amount": "IPL Laser",
              "detail": "3–5 sessions (minimal)",
              "note": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "richtext",
          "label": "",
          "background": "light",
          "anchorId": "richtext",
          "richContent": "<h2 style=\"font-family: Lora, Georgia, serif; font-weight: 500; color: rgb(15, 35, 64);\">At-Home Maintenance</h2><div><!--TgQPHd|[]-->Professional results are best maintained with a consistent daily routine using active ingredients.<!--TgQPHd|[]--><ul><li><strong>Morning<!--TgQPHd|[]--></strong>: Vitamin C serum for antioxidant protection and broad-spectrum SPF to prevent further UV damage.<!--TgQPHd|[]--><!--TgQPHd|[]--></li><li><strong>Evening<!--TgQPHd|[]--></strong>: Retinoids (Vitamin A) to increase cell turnover and hyaluronic acid for hydration.</li></ul></div>",
          "imagePath": "",
          "imagePos": "none",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": false
        }
      ]
    },
    {
      "slug": "body-contouring",
      "navLabel": "Body Contouring",
      "emoji": "📄",
      "enabled": true,
      "parent": "our-treatments",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Treatments",
          "background": "alt",
          "anchorId": "body-contouring-sculpting",
          "heading": "Body Contouring & Sculpting",
          "body": "Even with diet and exercise, most people have stubborn pockets of fat that seem impossible to lose. Associates in Women’s Health is proud to offer truSculpt® iD and SculpSure, revolutionary non-surgical, body-sculpting treatments that allows you to personalize your ideal body in as little as one 15-minute treatment. \n\nBody contouring technology is able to target and can destroy the targeted fat cells safely in minutes without affecting the skin’s surface. There is no recovery time following treatment, so you can resume your daily activities immediately. Most patients need multiple treatments to achieve optimal results.\n\n- Customizable treatment plans\n\n- Over 90% patient satisfaction rate\n\n- FDA cleared\n\n- Clinically proven to permanently eliminate fat cells",
          "imagePath": "images/TruSculpt/loveyourtruebody.png",
          "imagePosition": "left",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext",
          "richContent": "<h3>What is body sculpting?</h3><p>Body Sculpting is the latest nonsurgical procedure that’s clinically proven to target problem areas on the body that are resistant to diet and exercise, like cellulite-all with no downtime.</p><h3>How does body sculpting work?</h3><p>Body Sculpting targets fat cells under the skin without affecting the skin’s surface, raising the temperature of fat cells damaging their structural integrity. Fat cells are permanently removed and will not regenerate. Results can be seen as quickly as six weeks  </p><h3>Who is right for Body Sculpting?</h3><p>Body Sculpting is the ideal alternative for both women and men that live a healthy lifestyle but have problem areas that neither a NO-carb, NO-sugar diet nor any amount of crunches or 5K runs can resolve.</p><!--EndFragment-->\n\n",
          "imagePath": "images/TruSculpt/truSculpt-01.jpg",
          "imagePos": "right",
          "imageSize": "lg",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "richtext",
          "label": "",
          "background": "inherit",
          "anchorId": "richtext-2",
          "richContent": "<h3>How many treatments are required?</h3><p>Some patients see results with only 1 treatment, but for most 2 to 4 treatment sessions spaced 4 to 6 weeks apart are recommended to achieve optimal results.</p><h3>What can I expect? </h3><p>During a treatment, a small wand is applied to the problem area, and delivers safe and effective heat. While pain varies from patient-to-patient, most patients find the procedure comfortable and therapeutic. This is a no downtime procedure giving you the freedom to return to your daily activities immediately post treatment.</p><h3>Which is right for me - truSculpt® or SculpSure?</h3><p>We are very excited to offer two different options for body sculpting - truSculpt® or SculpSure. They are both effective in different areas. Our staff will discuss which option is right for you based on your individual needs.</p><!--EndFragment-->\n\n",
          "imagePath": "images/TruSculpt/truSculpt-02.png",
          "imagePos": "right",
          "imageSize": "lg",
          "imageCaption": "",
          "fullWidth": true
        },
        {
          "type": "two-col",
          "label": "",
          "background": "light",
          "anchorId": "two-col",
          "heading": "Plagued By Stubborn Neck Fat?",
          "body": "Have you ever thought of getting rid of fatty double chin but don’t want Lipo or surgery? truSculpt is an FDA-approved procedure that’s designed to address problem areas like the arms, thighs, abdomen, buttocks, and flanks and yes, even the chin!",
          "imagePath": "images/TruSculpt/neckfat-01.png",
          "imagePosition": "left",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "logo-strip",
          "label": "",
          "background": "dark",
          "anchorId": "logo-strip",
          "heading": "",
          "subtitle": "",
          "logoSize": "large",
          "items": [
            {
              "imagePath": "images/truSculpt.png",
              "alt": "",
              "caption": "",
              "linkUrl": ""
            },
            {
              "imagePath": "images/SculpSure.png",
              "alt": "",
              "caption": "",
              "linkUrl": ""
            }
          ]
        }
      ]
    }
  ],
  "aboutSections": [],
  "homeSections": [
    {
      "type": "logo-strip",
      "label": "",
      "background": "dark",
      "anchorId": "logo-strip",
      "heading": "",
      "subtitle": "",
      "logoSize": "large",
      "items": [
        {
          "imagePath": "logos/ehs_logo_white.svg",
          "alt": "Evexias",
          "caption": "",
          "linkUrl": ""
        },
        {
          "imagePath": "logos/truSculpt-Logo_wht.png",
          "alt": "truSculpt",
          "caption": "",
          "linkUrl": "https://cutera.com/us-en/products/trusculpt/"
        }
      ]
    }
  ],
  "footerBio": "",
  "animateStats": false,
  "contactSubmitLabel": "Submit",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public",
    "cp-3": "public",
    "cp-4": "public",
    "cp-5": "public"
  },
  "_savedAt": 1781644357790,
  "mapsApiKey": "",
  "fontDisplayCustom": "",
  "fontBodyCustom": ""
};
